// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace RuleForge.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260306143909_BaselineSchema")]
    partial class BaselineSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AppError", b =>
                {
                    b.Property<int>("AppErrorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppErrorId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<string>("Method")
                        .HasColumnType("text");

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.Property<string>("StackTrace")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("AppErrorId");

                    b.ToTable("AppErrors");
                });

            modelBuilder.Entity("AppUser", b =>
                {
                    b.Property<int>("AppUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AppUserId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSystemAccount")
                        .HasColumnType("boolean");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppUserId");

                    b.ToTable("AppUsers");
                });

            modelBuilder.Entity("Campaign", b =>
                {
                    b.Property<int>("CampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CampaignId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("OwnerAppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CampaignId");

                    b.ToTable("Campaigns");
                });

            modelBuilder.Entity("CampaignCollaborator", b =>
                {
                    b.Property<int>("CampaignCollaboratorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CampaignCollaboratorId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CampaignCollaboratorId");

                    b.ToTable("CampaignCollaborators");
                });

            modelBuilder.Entity("CampaignPlayer", b =>
                {
                    b.Property<int>("CampaignPlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CampaignPlayerId"));

                    b.Property<int>("AppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CampaignPlayerId");

                    b.ToTable("CampaignPlayers");
                });

            modelBuilder.Entity("Creature", b =>
                {
                    b.Property<int>("CreatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreatureId"));

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<string>("Alignment")
                        .HasColumnType("text");

                    b.Property<int?>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<string>("ChallengeRating")
                        .HasColumnType("text");

                    b.Property<int?>("Charisma")
                        .HasColumnType("integer");

                    b.Property<int?>("Constitution")
                        .HasColumnType("integer");

                    b.Property<string>("CreatureType")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Dexterity")
                        .HasColumnType("integer");

                    b.Property<int>("GameSystemId")
                        .HasColumnType("integer");

                    b.Property<int?>("HitPoints")
                        .HasColumnType("integer");

                    b.Property<int?>("Intelligence")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OwnerAppUserId")
                        .HasColumnType("integer");

                    b.Property<int?>("ProficiencyBonus")
                        .HasColumnType("integer");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SourceMaterialId")
                        .HasColumnType("integer");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<string>("Speed")
                        .HasColumnType("text");

                    b.Property<int?>("Strength")
                        .HasColumnType("integer");

                    b.Property<int?>("Wisdom")
                        .HasColumnType("integer");

                    b.HasKey("CreatureId");

                    b.ToTable("Creatures");
                });

            modelBuilder.Entity("CreatureAbility", b =>
                {
                    b.Property<int>("CreatureAbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CreatureAbilityId"));

                    b.Property<string>("AbilityType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreatureId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("CreatureAbilityId");

                    b.ToTable("CreatureAbilities");
                });

            modelBuilder.Entity("CurrencyDefinition", b =>
                {
                    b.Property<int>("CurrencyDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CurrencyDefinitionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("GameSystemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .HasColumnType("text");

                    b.HasKey("CurrencyDefinitionId");

                    b.ToTable("CurrencyDefinitions");
                });

            modelBuilder.Entity("FeatureRequest", b =>
                {
                    b.Property<int>("FeatureRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FeatureRequestId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Entity")
                        .HasColumnType("text");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.Property<string>("RequestedBy")
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FeatureRequestId");

                    b.ToTable("FeatureRequests");
                });

            modelBuilder.Entity("Friend", b =>
                {
                    b.Property<int>("FriendId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FriendId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserAId")
                        .HasColumnType("integer");

                    b.Property<int>("UserBId")
                        .HasColumnType("integer");

                    b.HasKey("FriendId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("FriendRequest", b =>
                {
                    b.Property<int>("FriendRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FriendRequestId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateResolvedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FromAppUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ToAppUserId")
                        .HasColumnType("integer");

                    b.HasKey("FriendRequestId");

                    b.ToTable("FriendRequests");
                });

            modelBuilder.Entity("GameSystem", b =>
                {
                    b.Property<int>("GameSystemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GameSystemId"));

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.HasKey("GameSystemId");

                    b.ToTable("GameSystems");
                });

            modelBuilder.Entity("Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<string>("ArmorCategory")
                        .HasColumnType("text");

                    b.Property<int?>("ArmorClass")
                        .HasColumnType("integer");

                    b.Property<string>("AttunementRequirement")
                        .HasColumnType("text");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("integer");

                    b.Property<int?>("ChargesCurrent")
                        .HasColumnType("integer");

                    b.Property<int?>("ChargesMax")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CostAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("CostCurrency")
                        .HasColumnType("text");

                    b.Property<int?>("CurrencyDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("DamageDice")
                        .HasColumnType("text");

                    b.Property<string>("DamageType")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Effect")
                        .HasColumnType("text");

                    b.Property<int>("GameSystemId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("boolean");

                    b.Property<int?>("ItemTypeDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OwnerAppUserId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("RangeLong")
                        .HasColumnType("integer");

                    b.Property<int?>("RangeNormal")
                        .HasColumnType("integer");

                    b.Property<string>("Rarity")
                        .HasColumnType("text");

                    b.Property<int?>("RarityDefinitionId")
                        .HasColumnType("integer");

                    b.Property<string>("RechargeRule")
                        .HasColumnType("text");

                    b.Property<bool>("RequiresAttunement")
                        .HasColumnType("boolean");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceBook")
                        .HasColumnType("text");

                    b.Property<int?>("SourceMaterialId")
                        .HasColumnType("integer");

                    b.Property<int?>("SourcePage")
                        .HasColumnType("integer");

                    b.Property<int>("SourceType")
                        .HasColumnType("integer");

                    b.Property<bool>("StealthDisadvantage")
                        .HasColumnType("boolean");

                    b.Property<int?>("StrengthRequirement")
                        .HasColumnType("integer");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<int?>("UsesPerDay")
                        .HasColumnType("integer");

                    b.Property<string>("VersatileDamageDice")
                        .HasColumnType("text");

                    b.Property<bool>("WeaponPropertyAmmunition")
                        .HasColumnType("boolean");

                    b.Property<bool>("WeaponPropertyFinesse")
                        .HasColumnType("boolean");

                    b.Property<bool>("WeaponPropertyHeavy")
                        .HasColumnType("boolean");

                    b.Property<bool>("WeaponPropertyLight")
                        .HasColumnType("boolean");

                    b.Property<bool>("WeaponPropertyLoading")
                        .HasColumnType("boolean");

                    b.Property<bool>("WeaponPropertyReach")
                        .HasColumnType("boolean");

                    b.Property<bool>("WeaponPropertyThrown")
                        .HasColumnType("boolean");

                    b.Property<bool>("WeaponPropertyTwoHanded")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("ItemTag", b =>
                {
                    b.Property<int>("ItemTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemTagId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("TagDefinitionId")
                        .HasColumnType("integer");

                    b.HasKey("ItemTagId");

                    b.ToTable("ItemTags");
                });

            modelBuilder.Entity("ItemTypeDefinition", b =>
                {
                    b.Property<int>("ItemTypeDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ItemTypeDefinitionId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("GameSystemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ItemTypeDefinitionId");

                    b.ToTable("ItemTypeDefinitions");
                });

            modelBuilder.Entity("Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NoteId"));

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("NoteId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("RarityDefinition", b =>
                {
                    b.Property<int>("RarityDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RarityDefinitionId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("GameSystemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("RarityDefinitionId");

                    b.ToTable("RarityDefinitions");
                });

            modelBuilder.Entity("SourceMaterial", b =>
                {
                    b.Property<int>("SourceMaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SourceMaterialId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameSystemId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsOfficial")
                        .HasColumnType("boolean");

                    b.Property<string>("Publisher")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SourceMaterialId");

                    b.ToTable("SourceMaterials");
                });

            modelBuilder.Entity("TagDefinition", b =>
                {
                    b.Property<int>("TagDefinitionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagDefinitionId"));

                    b.Property<DateTime>("DateCreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateDeletedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GameSystemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TagDefinitionId");

                    b.ToTable("TagDefinitions");
                });
#pragma warning restore 612, 618
        }
    }
}
